// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlsNjgRAA52h7fu860o4Y0IBrqRdMMI-c',
    appId: '1:209065184666:web:119a64204eea650644be23',
    messagingSenderId: '209065184666',
    projectId: 'spark-2da22',
    authDomain: 'spark-2da22.firebaseapp.com',
    storageBucket: 'spark-2da22.firebasestorage.app',
    measurementId: 'G-040QF4LVV2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp6p3NAY6HFc2Txabjyq10nVY7eU-1tgA',
    appId: '1:209065184666:android:4f365f23ee056cc244be23',
    messagingSenderId: '209065184666',
    projectId: 'spark-2da22',
    storageBucket: 'spark-2da22.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1iwOToBQ-cPkMqz_8DdQEGBVdl08bgII',
    appId: '1:209065184666:ios:4c49916545ebdf0944be23',
    messagingSenderId: '209065184666',
    projectId: 'spark-2da22',
    storageBucket: 'spark-2da22.firebasestorage.app',
    iosBundleId: 'com.example.clinicConnectFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1iwOToBQ-cPkMqz_8DdQEGBVdl08bgII',
    appId: '1:209065184666:ios:4c49916545ebdf0944be23',
    messagingSenderId: '209065184666',
    projectId: 'spark-2da22',
    storageBucket: 'spark-2da22.firebasestorage.app',
    iosBundleId: 'com.example.clinicConnectFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlsNjgRAA52h7fu860o4Y0IBrqRdMMI-c',
    appId: '1:209065184666:web:f35853844f91648d44be23',
    messagingSenderId: '209065184666',
    projectId: 'spark-2da22',
    authDomain: 'spark-2da22.firebaseapp.com',
    storageBucket: 'spark-2da22.firebasestorage.app',
    measurementId: 'G-NZBKD1RGSJ',
  );

}